Repository C-KLex/GitEducation, pull requests merged in 2023-06, with the labels that each got.

#1 Finished Software Design Doc
  doc/design_doc.md
Labels: documentation

#3 Coding Style & Naming Convention
  code_style_and_naming.md
Labels: documentation

#2 Documentation Guideline
  documentation_guide.md
Labels: documentation

#5 ‘get_week_day()’ First PR
  Calendar_CLI/Calendar.py
Labels: enhancement

#10 `get_week_day()` Second PR
  Calendar_CLI/Calendar.py
Labels: bug

#7 `number_of_leap_years` and `main` first PR
  Calendar_CLI/Calendar.py
  Calendar_CLI/Main.py
Labels: documentation

#6 first PR for number_of_days()
  Calendar_CLI/Calendar.py
Labels: enhancement

#8 log() first PR
  Calendar_CLI/Log.py
Labels: enhancement

#12 `number_of_days()` second PR bug fix
  Calendar_CLI/Calendar.py
Labels: bug

#14 `log()` second PR
  Calendar_CLI/Log.py
Labels: bug
